# This is a basic workflow to help you get started with Actions

name: Init-Mirror

# Controls when the workflow will run
on:

  workflow_dispatch:

jobs:

  check_lock:
    runs-on: ubuntu-latest
    outputs:
      initialized: ${{ steps.changed_pkgs.outputs.initialized }}
    steps:
      - uses: actions/checkout@v3

      - name: Check Init lock
        id: check_init_lock
        run: |
          if [ ! -f init.lock ]
          then
            echo "initialized=false" >> $GITHUB_OUTPUT
          else
            echo "tiup-${{ github.repository_owner }} mirror has been initialized"
            echo "Initialized=true" >> $GITHUB_OUTPUT
          fi

  init-mirror:
    runs-on: ubuntu-latest
    needs: [check_lock]
    if: needs.check_lock.outputs.initialized == 'false'
    steps:
      - uses: actions/checkout@v3

      - name: Check Init lock
        run: |
          if [ -f init.lock ]
          then
            echo "tiup-${{ github.repository_owner }} mirror has been initialized"
            exit 2
          fi

          echo "clean old mirror"
          rm -rf docs tiup-* packages

        
      - id: Install-tiup
        name: Install tiup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh

      - id: Init-mirror
        name: Init tiup-community mirror
        run: |
          source ~/.profile
          mkdir -p tiup-${{ github.repository_owner }} ~/.tiup/keys
          tiup mirror init tiup-${{ github.repository_owner }}
          tiup mirror set tiup-${{ github.repository_owner }}
          
          tiup mirror genkey -n ${{ github.repository_owner }}

          cp ~/.tiup/keys/${{ github.repository_owner }}.json tiup-${{ github.repository_owner }}/keys/

          tiup mirror grant  ${{ github.repository_owner }} -k tiup-${{ github.repository_owner }}/keys/${{ github.repository_owner }}.json
        
      - name: Encrypt keys
        run: |
          mkdir -p ~/.tiup/keys
          echo ${{ secrets.TIUP_KEY}} > ~/.tiup/keys/tiup.key
          for file in tiup-${{ github.repository_owner }}/keys/*
          do
            if [[ $file == *json ]]
            then
              openssl aes-256-cbc -a -salt -pbkdf2 -in $file -out $file.encrypt -kfile ~/.tiup/keys/tiup.key 
            fi
          done
          rm -rf tiup-${{ github.repository_owner }}/keys/*json
          tree
      
      - name: Create github page docs and lock
        run: |
          ln -s tiup-${{ github.repository_owner }} docs
          touch init.lock
      
      - name: Push Mirror
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: init tiup-community mirror ${{ github.repository_owner }}
