# This is a basic workflow to help you get started with Actions

name: Init-Mirror

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  init-mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - id: install-tiup
        name: Install tiup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh

      - id: init-mirror
        name: Init tiup-community mirror
        run: |
          source ~/.profile
          mkdir -p tiup-community 
          tiup mirror init tiup-community
          tiup mirror set tiup-community
          tiup mirror grant ${{ github.repository_owne }}

      - name: Encrypted keys
        working-directory: ./tiup-community

        run: |
          mkdir -p ~/.tiup/keys tiup-community/encrypt_keys
          echo ${{ secrets.TIUP_KEY}} > ~/.tiup/keys/tiup.key
          for file in tiup-community/keys/*
          do
            if test -f tiup-community/keys/$file
            then
              openssl enc -aes-256-cbc -in tiup-community/keys/$file -out tiup-community/encrypt_keys/$file
            fi
          done
          rm -rf keys
          tree

