# This is a basic workflow to help you get started with Actions

name: Init-Mirror

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  init-mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - id: install-tiup
        name: Install tiup
        run: |
          TMP_DIR=`mktemp -d`
          export TIUP_HOME="$TMP_DIR/home"
          echo ::set-output name=TIUP_HOME::$TIUP_HOME
          rm -rf $TIUP_HOME && mkdir -p $TIUP_HOME/{bin,keys}
          curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh

      - id: init-mirror
        name: Init tiup-community mirror
        run: |
          source ~/.profile
          mkdir -p tiup-community 
          tiup mirror init tiup-community
          tiup mirror set tiup-community
          echo ::set-output name=TIUP_HOME::$TIUP_HOME
          tiup mirrot grant ${{ github.repository_owne }}

          tree

