# This is a basic workflow to help you get started with Actions

name: Init-Mirror

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  init-mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check Init lock
        run: |
          if [ -f init.lock ]
          then
            echo "tiup-${{ github.repository_owner }} mirror has been initialized"
            exit 2
          fi

          echo "clean old mirror"
          rm -rf docs tiup-*

        
      - id: Install-tiup
        name: Install tiup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh

      - id: Init-mirror
        name: Init tiup-community mirror
        run: |
          source ~/.profile
          mkdir -p tiup-${{ github.repository_owner }} ~/.tiup/keys
          tiup mirror init tiup-${{ github.repository_owner }}
          tiup mirror set tiup-${{ github.repository_owner }}
          
          tiup mirror genkey -n ${{ github.repository_owner }}

          cp ~/.tiup/keys/${{ github.repository_owner }}.json tiup-${{ github.repository_owner }}/keys/

          tiup mirror grant  ${{ github.repository_owner }} -k tiup-${{ github.repository_owner }}/keys/${{ github.repository_owner }}.json
        
      - name: Encrypt keys
        run: |
          mkdir -p ~/.tiup/keys
          echo ${{ secrets.TIUP_KEY}} > ~/.tiup/keys/tiup.key
          for file in tiup-${{ github.repository_owner }}/keys/*
          do
            if [[ $file == *json ]]
            then
              openssl enc -aes-256-cbc -md md5 -in $file -out $file.encrypt -k ~/.tiup/keys/tiup.key
            fi
          done
          rm -rf tiup-${{ github.repository_owner }}/keys/*json
          tree
      
      - name: Create github page docs and lock
        run: |
          ln -s tiup-${{ github.repository_owner }} docs
          touch init.lock
      
      - name: Push Mirror
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: init tiup-community mirror ${{ github.repository_owner }}
