# This is a basic workflow to help you get started with Actions

name: Publish component

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-component:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check Init lock
        run: |
          if [ ! -f init.lock ]
          then
            echo "tiup-${{ github.repository_owner }} mirror uninitialized"
            exit 2
          fi

      - id: Install-tiup
        name: Install tiup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh

      - name: Decrypt keys
        run: |
          mkdir -p ~/.tiup/keys/
          echo ${{ secrets.TIUP_KEY}} > ~/.tiup/keys/tiup.key
          for file in tiup-${{ github.repository_owner }}/keys/*
          do
            if [[ $file == *encrypt ]]
            then
              de_file=${file//.encrypt/}
              echo $de_file
              openssl enc -aes-256-cbc -d -in $file -out $de_file -k ~/.tiup/keys/tiup.key
            fi
          done
          rm -rf tiup-${{ github.repository_owner }}/keys/*encrypt
          tree
      
      # - id: Build-component
      #   name: build component


      # - id: Publish-component


      # - name: Encrypt keys
      #   run: |
      #     mkdir -p ~/.tiup/keys
      #     echo ${{ secrets.TIUP_KEY}} > ~/.tiup/keys/tiup.key
      #     for file in tiup-${{ github.repository_owner }}/keys/*
      #     do
      #       if [[ $file == *json ]]
      #       then
      #         openssl enc -aes-256-cbc -in $file -out $file.encrypt -k ~/.tiup/keys/tiup.key
      #       fi
      #     done
      #     rm -rf tiup-${{ github.repository_owner }}/keys/*json
      #     tree
      
      # - name: Push Mirror
      #   uses: actions-js/push@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     message: publish component to ${{ github.repository_owner }}